#app parameters
master: "local[*]"
directory: "c:\\data\\"
defaultKeyspace: "test_keyspace"
offsetOverride: "EARLIEST"
insertStatement: "INSERT INTO %s.%s (%s) VALUES (%s)"

#spark parameters
sparkConfigs:
    spark.cassandra.connection.host: "127.0.0.1"
    spark.cassandra.auth.username: "cassandra"
    spark.cassandra.auth.password: "cassandra"
    #spark.cassandra.connection.local_dc: --use if you have more than one data center
    spark.cassandra.connection.keep_alive_ms: "180000"
    spark.cassandra.input.consistency.level: "LOCAL_QUORUM"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
#kafka configs
kafkaAppConfigs:
    obj1App: !app.KafkaInfo
        brokerList: "localhost:9092"
        topicList: "OBJ1"
        batchInterval: "10"
        batchIntervalUnit: "Seconds"
#cassandra tables
cassandraTables:
    checkpoint: !app.TableInfo
        table: "checkpoint"
        keyspace: "test_keyspace"
        fields: "app_name,topic_name,partition,checkpoint_time,start_offset,end_offset"
    batch_metrics: !app.TableInfo
        table: "batch_metrics"
        keyspace: "test_keyspace"
        fields: "batch_date,app_name,batch_time,status,application_id,master,sched_delay,prcsg_delay,total_delay,record_count,throughput,tot_sched_delay_dly,tot_prcsg_delay_dly,total_delay_dly,tot_recs_prcsd_dly,avg_throughput_dly"
    job_metrics: !app.TableInfo
        table: "job_metrics"
        keyspace: "test_keyspace"
        fields: "batch_date,app_name,job_id,batch_time,application_id,master,job_info,job_start_time,job_end_time,prcsg_time"